### ISSUE TITLE
Filter in imagetoid for property git_branch

### ISSUE THREAD

**Issue by sandzwerg** [sapcc/baremetal_temper#5]
The image IDs used should not only consider the age and name of the image, but also the properties. Proper images should have a property `git_branch: master` set. I think it should be possible to add this in the getimageid function somewhere here: https://github.com/sapcc/baremetal_temper/blob/7fa2d60ca09e3d9b39e72b5cec6fca71da63e6d9/pkg/node/openstack.go#L329
But I'm not fluent in go to propose this change myself

**Comment by stefanhipfel** [comment]
https://github.com/sapcc/baremetal_temper/commit/ddeb219955bdbddd4366c7e7ff3d5705df09b53a
