### ISSUE TITLE
Missing file does not lead to an error

### ISSUE THREAD

**Issue by sandzwerg** [sapcc/baremetal_temper#7]
If the temper is not finding a file it does not give an error or even a warning but fails down the road with followup issues, example

```
go run main.go run -w 5 -t ironic.create -t ironic.validate -t ironic.prepare -q BB425 --node-status planned -c etc/config-eu-de-2.yml -s=false -l 10
WARN[0000] did not find boot image for cable check. run check without it 
ERRO[0000] error loading nodes: Get "https:///api/dcim/devices/?q=BB425&role=server&status=planned": http: no Host in request URL 
ERRO[0000] error loading nodes: Get "https:///api/dcim/devices/?q=BB425&role=server&status=planned": http: no Host in request URL
```

-> The filename was wrong thus the host was empty, it would be nice if there would be any kind of warning or error that the file wasn't found.

**Comment by stefanhipfel** [comment]
https://github.com/sapcc/baremetal_temper/commit/0f0a7ce250620a0e58730b5068ba463de3512ead
